### ISSUE TITLE
No Implementation Error received

### ISSUE THREAD

**Issue by prplrhd** [psincler/Vera-MyQGateway#2]
Thanks for giving this a go... been waiting a while for a champion for this old plugin.

Tried two attempts. First was to remove the old app, then copy files, create device, add in login info. Second attempt was put back the original plugin, copy files, create device, add login info. Same result in both cases. After adding login info, the dreaded red "X" error box appears with "ERROR: No Implementation" 

08      04/05/21 17:33:10.812   JobHandler_LuaUPnP::HandleActionRequest device: 121 service: urn:macrho-com:serviceId:MyQGateway1 action: SetUsernamePassword <0x73138520>
08      04/05/21 17:33:10.812   JobHandler_LuaUPnP::HandleActionRequest argument DeviceNum=121 <0x73138520>
08      04/05/21 17:33:10.812   JobHandler_LuaUPnP::HandleActionRequest argument serviceId=urn:macrho-com:serviceId:MyQGateway1 <0x73138520>
08      04/05/21 17:33:10.813   JobHandler_LuaUPnP::HandleActionRequest argument action=SetUsernamePassword <0x73138520>
08      04/05/21 17:33:10.813   JobHandler_LuaUPnP::HandleActionRequest argument newUsername=XXXX <0x73138520>
08      04/05/21 17:33:10.813   JobHandler_LuaUPnP::HandleActionRequest argument newPassword=XXXX <0x73138520>
02      04/05/21 17:33:10.813   Device_LuaUPnP::HandleActionRequest 121 none of the 1 implementations handled it <0x73138520>
02      04/05/21 17:33:10.813   JobHandler_LuaUPnP::RunAction device 121 action urn:macrho-com:serviceId:MyQGateway1/SetUsernamePassword failed with 501/No implementation <0x73138520>

the code puts id and password in log in plain text, XXXX here represents what was the correct values in the log. Verified the files appear to have been copied over ok. 

Did I miss something?

Matt

**Comment by prplrhd** [comment]
Update

Made some progress as follows (perhaps will help others)
- I started with the original plugin that had been working and failed due to the login changes implemented by the MyQ folks
- I initially copied the files up and tried to work with the new garage device. After that failed, I removed not only the old garage door device but the entire former MyQ plugin.
- What is working better is to clear out everything, install the old MyQ plugin, then copy these new files.

I now have the original plugin, and the new files and the new device. The new device is able to authenticate, and the open/close commands work on the newly created garage door device and are recognized by the plugin. Got some problems with the icons - when I copied back the new code, the icons disappeared - and the new hybrid plugin is telling me the "Opener brand not configured" but other than the rough edges it's functional.

**Comment by miketanji** [comment]
Matt, thank you for the tips. I had same problem and this helped. Have same issue with no icons. I am not experienced with a manual device install but the icons folder posted here said do not upload. I did configure opener brand before I uploaded new files and did not have issue. Opener brand can be edited on variables page. Please post update if you figure out icon issue.

Thanks,
Mike

**Comment by psincler** [comment]
Yeah, apologies for the rough edges.  I got it working just well enough to suit my needs.  If icons are missing, suggest you look for them on the Vera, see if maybe they are corrupted somehow?  Also, I believe opener brand should have been removed entirely since I no longer saw different endpoints to hit based on brand.  If you're still seeing things around that, you may have some old/leftover files running around somewhere.
